### ISSUE TITLE
Is there a schedule for code release？

### ISSUE THREAD

**Issue by NLP-LH** [cshizhe/hgr_v2t#1]

**Comment by jingruhou** [comment]
估计还早...

**Comment by cshizhe** [comment]
Thanks for your attention. We will release codes before June. Please stay tuned.

**Comment by mengliu1991** [comment]
@cshizhe When the code will be released?

**Comment by TianyuLee** [comment]
@cshizhe Could you release your codes?

**Comment by cshizhe** [comment]
> @cshizhe Could you release your codes?

I am preparing the codes, data and instructions and will release them this week.

**Comment by TianyuLee** [comment]
> > @cshizhe Could you release your codes?
> 
> I am preparing the codes, data and instructions and will release them this week.

Thank you very much!

**Comment by cshizhe** [comment]
Hi all,

I have released our codes and instructions. The datasets will also be released soon, which are delayed a little bit due to network issues.

**Comment by TianyuLee** [comment]
Hi cshizhe,

The link of features is invalid now, could you check it?
