### ISSUE TITLE
Questions about the MSR-VTT dataset

### ISSUE THREAD

**Issue by Li-Zheng-94** [cshizhe/hgr_v2t#10]
Hi, Shizhe, thanks for your great work. I downloaded the MSR-VTT dataset you provided, and I have a question. I found that not every video corresponds to 20 captions. Some videos only correspond to less than 20 captions. I would like to ask if you specifically selected these captions and how to choose them?

**Comment by cshizhe** [comment]
There are redundant captions for some videos in MSRVTT dataset. I have removed these redundant captions.
