### ISSUE TITLE
Question about inconsistent results with the other papers

### ISSUE THREAD

**Issue by chewry** [cshizhe/hgr_v2t#11]
Hi cshizhe.
In your paper, video-to-text retrieval results of all methods on **TGIF** are much lower than the results in the PVSE paper. 
Because there is no description about the result, I can't understand the discrepancy of the results.
Can you explain about this?
I do have to train your code on TGIF and get the result but I think it's more certain.

Thank you in advance.

**Comment by cshizhe** [comment]
Hi, I cited the results from [the PVSE paper in the CVPR 2019 proceeding](https://openaccess.thecvf.com/content_CVPR_2019/papers/Song_Polysemous_Visual-Semantic_Embedding_for_Cross-Modal_Retrieval_CVPR_2019_paper.pdf). I just realized that the results in their camera ready paper are different from the results in their recent Arxiv version.

**Comment by chewry** [comment]
Thank you for your reply. 
Even for their recent results, your method still shows better performance.
My confusion about the discrepancy is resolved.
I will close this issue. thank you.
