### ISSUE TITLE
About other dataset

### ISSUE THREAD

**Issue by MinamiKotoka** [cshizhe/hgr_v2t#15]
Hi, I'm very interested in your work, and I want to use other datasets like Charades on your model. But there are several files like annotations which other datasets don't have. What should I do could get these annotations and how to get the role graph? Could you provide your tools metioned in your paper? Thank you very much if you can reply me.

**Comment by cshizhe** [comment]
The instructions are already available:
https://github.com/cshizhe/hgr_v2t#semantic-graph-construction
