### ISSUE TITLE
About semantic_role_labeling.py

### ISSUE THREAD

**Issue by MinamiKotoka** [cshizhe/hgr_v2t#17]
Hi, when I generate my own rolegraph, there are something wrong. With the predictor's model adress `https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz` you provided in `semantic_role_labeling.py`, I got the predictor's output like `{'verbs': [{'verb': 'talks', 'description': 'a woman talks about a futuristic bicycle design', 'tags': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']}], 'words': ['a', 'woman', 'talks', 'about', 'a', 'futuristic', 'bicycle', 'design']}`, all tags are `O`. So are there someting wrong with the model? I try other models like `https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.03.24.tar.gz`, which is used in semantic roles labeling provided in `https://demo.allennlp.org/semantic-role-labeling/MjMyODEwNg==`, it works correctly, the output is `{'verbs': [{'verb': 'is', 'description': 'someone [V: is] blowing a little boys face with a leaf blower', 'tags': ['O', 'B-V', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']}, {'verb': 'blowing', 'description': '[ARG0: someone] is [V: blowing] [ARG1: a little boys face] [ARGM-MNR: with a leaf blower]', 'tags': ['B-ARG0', 'O', 'B-V', 'B-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'B-ARGM-MNR', 'I-ARGM-MNR', 'I-ARGM-MNR', 'I-ARGM-MNR']}, {'verb': 'face', 'description': 'someone is blowing [ARG0: a little boys] [V: face] with a leaf blower', 'tags': ['O', 'O', 'O', 'B-ARG0', 'I-ARG0', 'I-ARG0', 'B-V', 'O', 'O', 'O', 'O']}], 'words': ['someone', 'is', 'blowing', 'a', 'little', 'boys', 'face', 'with', 'a', 'leaf', 'blower']}`.

**Comment by cshizhe** [comment]
The API of AllenNLP might be changed so that the previous model doesn't work now.
It is good to know that the new model works.
