### ISSUE TITLE
About the recurrence of paper results

### ISSUE THREAD

**Issue by Palette25** [cshizhe/hgr_v2t#22]
Thank you for your great codes ! And after running your codes in my server for several times, I am surprised to find out that I cannot reproduce your result in paper. The best result of final recall sum that I got in MSRVTT is 170.1 while your paper's result is 172.4, and i did not modify anything of your codes...
Could you please share the best parameters of your codes ? or introduce the solution of my problem ?

**Comment by cshizhe** [comment]
Please find a similar issue [here](https://github.com/cshizhe/hgr_v2t/issues/7).

**Comment by Palette25** [comment]
> Please find a similar issue [here](https://github.com/cshizhe/hgr_v2t/issues/7).

Got it ! Thank you for your reply~
