### ISSUE TITLE
Youtube2Text data set

### ISSUE THREAD

**Issue by haoshuai714** [cshizhe/hgr_v2t#27]
Recently I saw your paper fine-video-text Retrieval with Hierarchical Graph Reasoning. I saw you used Youtube2Text dataset in your paper. However, I did not find the video features and sentence features of Youtube2Text data set in baidu cloud link. Could you please provide me with the download link of Youtube2Text data set? Thank you very much!

**Comment by cshizhe** [comment]
It is the MSVD dataset.
