### ISSUE TITLE
Can you provide the split information of Vatex dataset?

### ISSUE THREAD

**Issue by HanielF** [cshizhe/hgr_v2t#28]
I find that the vatex dataset you used in hgr is VATEX v1.0 which does not provide the annotations on testing set.
Then you randomly split the validation set into two equal parts with 1,500 videos as validation set and other 1,500 videos as testing set. 
I want to follow your dataset partitioning, but i can not find any split information in this repo.
Could you please provide the 'csv' or 'json' files of vatex dataset which contain the partition information.

**Comment by cshizhe** [comment]
It is in the dataset download link: https://github.com/cshizhe/hgr_v2t#datasets

**Comment by HanielF** [comment]
Thanks for your help!
