### ISSUE TITLE
VATEX  has no Resnet152 feature

### ISSUE THREAD

**Issue by LetsGoFir** [cshizhe/hgr_v2t#4]
```
OSError: Unable to open file (unable to open file: name = 'data/VATEX/ordered_feature/SA/resnet152.pth/trn_ft.hdf5'
````

Could you tell me to use I3D feature?

**Comment by LetsGoFir** [comment]
And for other datasets
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/MSRVTT/results/RET.released/mlmatch/vis.resnet152.pth.txt.bigru.16role.gcn.1L.attn.1024.loss.bi.af.embed.4.glove.init/../../word_embeds.glove42b.th'
FileNotFoundError: [Errno 2] No such file or directory: 'data/TGIF/results/RET.released/mlmatch/vis.resnet152.pth.txt.bigru.16role.gcn.1L.attn.1024.loss.bi.af.embed.4.glove.init/../../word_embeds.glove42b.th'

**Comment by cshizhe** [comment]
> And for other datasets
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'data/MSRVTT/results/RET.released/mlmatch/vis.resnet152.pth.txt.bigru.16role.gcn.1L.attn.1024.loss.bi.af.embed.4.glove.init/../../word_embeds.glove42b.th'
> FileNotFoundError: [Errno 2] No such file or directory: 'data/TGIF/results/RET.released/mlmatch/vis.resnet152.pth.txt.bigru.16role.gcn.1L.attn.1024.loss.bi.af.embed.4.glove.init/../../word_embeds.glove42b.th'
> ```



> ```
> OSError: Unable to open file (unable to open file: name = 'data/VATEX/ordered_feature/SA/resnet152.pth/trn_ft.hdf5'
> ```
> 
> Could you tell me to use I3D feature?

1. We use i3d features which are uploaded in the VATEX directory. You should modify the path configs according to your dataset locations.

2. The word embeddings for initialization are uploaded in the results directory.

**Comment by LetsGoFir** [comment]
> > And for other datasets
> > ```
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/MSRVTT/results/RET.released/mlmatch/vis.resnet152.pth.txt.bigru.16role.gcn.1L.attn.1024.loss.bi.af.embed.4.glove.init/../../word_embeds.glove42b.th'
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/TGIF/results/RET.released/mlmatch/vis.resnet152.pth.txt.bigru.16role.gcn.1L.attn.1024.loss.bi.af.embed.4.glove.init/../../word_embeds.glove42b.th'
> > ```
> 
> > ```
> > OSError: Unable to open file (unable to open file: name = 'data/VATEX/ordered_feature/SA/resnet152.pth/trn_ft.hdf5'
> > ```
> > 
> > 
> > Could you tell me to use I3D feature?
> 
> 1. We use i3d features which are uploaded in the VATEX directory. You should modify the path configs according to your dataset locations.
> 2. The word embeddings for initialization are uploaded in the results directory.

I changed the 'RET.released' to 'RET' but got a 'size mismatch' error when forwarding, then I changed the fts_dim from [2048] to [1024], and it runs well!
Thanks~
