### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by mengliu1991** [cshizhe/hgr_v2t#5]
Hi,
I click the  BaiduNetdisk url, but it appears the following information:

此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！

**Comment by cshizhe** [comment]
> Hi,
> I click the BaiduNetdisk url, but it appears the following information:
> 
> 此链接分享内容可能因为涉及侵权、色情、反动、低俗等信息，无法访问！

That is so weird...
I uploaded the datasets again. You could use the new link in README.
