### ISSUE TITLE
about the frame rate

### ISSUE THREAD

**Issue by TianyuLee** [cshizhe/hgr_v2t#6]
Hi, cshizhe

I find that the number_of_feature/video_duration of videos are different, can you tell me the temporal interval of visual features?

Thanks

**Comment by Alen-T** [comment]
I want to know how you extract I3D features from a video. This I3D feature only uses RGB or flow and RGB？ Can you provide code to extract features?  Thanks!

**Comment by cshizhe** [comment]
For the resnet features, we extract the feature every 32 frames (for TGIF dataset, 8 frames).
For the I3D feature, we use the provided features from the VATEX team.

**Comment by pandababyer** [comment]
@cshizhe hello shizhe ! thanks for share the wonderful work and the code you write is like poem :)  I found that the vide clip in video0 is from 137.72 to 149.44 which means is about 12s duration  and 280 frames. But I find the corresponding feature shape in trn_ft.hdf5 is 19*2048. if I downsample as you say(every 32 frames) it should be 8 frame. It confused me a lot. Looking forward to your reply, thx.

**Comment by cshizhe** [comment]
> @cshizhe hello shizhe ! thanks for share the wonderful work and the code you write is like poem :) I found that the vide clip in video0 is from 137.72 to 149.44 which means is about 12s duration and 280 frames. But I find the corresponding feature shape in trn_ft.hdf5 is 19*2048. if I downsample as you say(every 32 frames) it should be 8 frame. It confused me a lot. Looking forward to your reply, thx.

Sorry about my mistake in previous reply. The resnet feature is extracted every 16 frames for MSRVTT dataset. For example, the video0 contains 300 frames, and the extracted feature size is 19 (18.75 = 300/16).
