### ISSUE TITLE
Problem about allennlp: "srl_bert is not a registered name for Model"

### ISSUE THREAD

**Issue by mysuli2333** [cshizhe/hgr_v2t#8]
The pretrained model "bert-base-srl-2019.06.17.tar.gz" seems not to be applicable for the latest version of allennlp

**Comment by BerengarChen** [comment]
Came up with the same problem.(have tried allennlp 0.9.0 and 1.0.0rc1)
Are there any possible solutions?

**Comment by BerengarChen** [comment]
Got the same problem on allennlp 0.9.0 and 1.0.0rc1.
Are there any possible solutions?

**Comment by zfchenUnique** [comment]
Meet the same problem and finally found the problem is that I have not successfully installed the package. Please try "pip install allennlp==1.0.0 allennlp-models==1.0.0". https://demo.allennlp.org/semantic-role-labeling/
